### PR TITLE
MM-55262: Add first draft of ceiling tests v1

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
Uploading the first draft of the first version of the ceiling tests. I still need to structure an archival of the config and result files for each test in individual directories, but I promised to open this PR today, so here we are :) I'll keep working on it next week. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55262

### CODE REVIEW

**Comment by agarciamontoro** [comment]
This is ready for review now.

**Comment by agarciamontoro** [comment]
Sorry, sorry, `ceiling-tests/v1/README.md` :nerd_face: https://github.com/mattermost/performance-reports/pull/4/files#diff-1d83b32e68cfa2bcdd79e20827ed673cd73bb2cf24db4c3b1def285f436c5299 Just 532 lines, not that bad

**Comment by agnivade** [comment]
Oh wow great work there! Sorry I didn't go through it line by line, but very thorough and comprehensive work looking at a high level!

**Comment by streamer45** [comment]
@agarciamontoro Would it make sense to include a bit more info on load balancer specs (e.g. nginx version) and related configs? After all it's a crucial part of any multi-instance deployments.

**Pull request merged**
